---
# tasks file for tomcat_installation_role
- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600 

- name: Install Java
  apt:
    name: openjdk-11-jdk
    state: present

- name: Download Tomcat
  get_url:
    url: "{{ TOMCAT9_URL }}"
    dest: /tmp/
    validate_certs: no

- name: Creating Apache Tomcat home directory.
  command: mkdir /opt/tomcat   
    
- name: Extract Tomcat
  shell: tar -xzvf /tmp/apache-tomcat-*tar.gz -C /opt/tomcat --strip-components=1

- name: overwrite localhost in conf/Catalina
  copy:
    src: localhost/
    dest: /opt/tomcat/conf/Catalina/localhost

- name: overwrite localhost in conf/Catalina
  copy:
    src: tomcat-users.xml
    dest: /opt/tomcat/conf/tomcat-users.xml

- name: Start Tomcat
  shell: /opt/tomcat/bin/startup.sh
  ignore_errors: true

- name: Wait for Tomcat to start
  wait_for:
    host: localhost
    port: 8080
    state: started

- name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
  tags: test
  uri:
    url: http://localhost:8080
  register: result
  until: "result.status == 200"
  retries: 5
  delay: 10